services:
  app:
    build: .
    container_name: github-backend
    ports:
      - "3000:3000"
      - "3001:3000"
      - "3002:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=file:./prisma/dev.db
    volumes:
      - ./prisma:/app/prisma
    restart: unless-stopped
